### ISSUE TITLE
Create directory "images/documents"

### ISSUE THREAD

**Issue by C-Lodder** [web-tiki/joomla-article-custom-field#3]
Currently, the following is being used:

```
directory="images/documents"
```

If this path doesn't exist, a yellow alert/warning message will be shown.
This directory needs to be created when the plugin is installed

See: https://docs.joomla.org/J2.5:Managing_Component_Updates_%28Script.php%29

**Comment by web-tiki** [comment]
I was thinking of removing that field to keep it simple. 
And give appropriate doc in the readme file to add fields.

**Comment by C-Lodder** [comment]
If this plugin is for users to download and install on their own site, I'd recommend creating the directory when the plugin is installed. You could also add a parameter in the plugin options to allow user to upload their files in this directory

**Comment by web-tiki** [comment]
This doesn't need to be done anymore as the fielsd using this dierectory has been deleted.
